### PR TITLE
Use NVM and configure CI.

### LINKED ISSUE #28: Automate fractal build and pages publishing
It would be nice if the fractal build and publishing to GitHub pages was automated through TravisCI.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #28

### CODE REVIEW

**Comment by richardbporter** [comment]
Let me know what you think of this. I'd be happy to split up into separate, smaller PRs. Here is a summary:

- Create an .nvmrc file and document usage. This provides consistency across environments.
- Add NPM scripts and document both ways of building the system.
- Install dependencies with NVM-managed Node, as well as compile (gulp).
- Remove the entire docs/ directory from the repo. The idea here is that it can be built locally and in CI without having to track every change in VCS. Travis could push a build artifact to releases that contains the docs/ directory if that is desired.
- Initialize TravisCI integration. Requires further work since PR's do not run deployments. The idea is that Travis will push to a separate gh-pages branch which contains the docs/ directory. It will run automatically on every push to master.

**Comment by GaryRidgway** [comment]
Got everything up and running with the instructions in the readme. Had to run npm install before i ran gulp watch because it threw an error.

**Comment by bspeare** [comment]
@richardbporter Thanks for putting this together.   If I want to work on this locally and view the HDS with live browser reloading do you still recommend using `gulp watch`?

**Comment by richardbporter** [comment]
I'm not sure. How were you doing that?

**Comment by bspeare** [comment]
`gulp watch` still works with your updates.  It runs the tasks outlined in the gulp file and I'm just wondering if that should be a part of the `npm run start` command or not.

**Comment by richardbporter** [comment]
I don't know. I can look into that more. I'm seeing the fractal server restart on every change though:

```
12:36:33] Using gulpfile ~/Sites/hds/gulpfile.js
[12:36:33] Starting 'watch'...
[12:36:33] Starting 'assetsCopy'...
[12:36:33] Starting 'watchFiles'...
[12:36:33] Finished 'assetsCopy' after 374 ms
[12:36:43] Starting 'css'...
[12:36:43] Starting 'fractalStart'...
✔ Fractal server is now running at http://localhost:3000
[12:36:43] Finished 'fractalStart' after 583 ms
[12:36:44] Finished 'css' after 1.11 s
[12:37:31] Starting 'css'...
[12:37:31] Starting 'fractalStart'...
✔ Fractal server is now running at http://localhost:3003
[12:37:31] Finished 'fractalStart' after 97 ms
[12:37:31] Finished 'css' after 465 ms
```

I can play around with adding the `--sync` option to the `fractal start` command.

**Comment by bspeare** [comment]
I'm probably just using the wrong command.   Are you using `npm run watch` there?

**Comment by richardbporter** [comment]
Yep, I just changed it to make it more accurate. I think either should work as they did before, either `gulp watch` or `npm run watch`.

**Comment by bspeare** [comment]
Great!  So any future code updates to the repo will build out and publish to the github pages?

**Comment by richardbporter** [comment]
Yes, but I’ll probably need to tweak a few things after this gets merged into master. I can't test the push to the gh-pages branch because it does not trigger on PRs. If `gulp watch` works for you and you're ok with the NVM + gitignore changes, this could be merged and follow-up tasks created later.

The gitignore changes basically save developers from having to commit the output from the `fractal build` command and avoids merge conflicts.

**Comment by richardbporter** [comment]
Sounds good. If this causes any regressions, let me know and I'll help fix and/or back out of this.

**Pull request merged**
